### ISSUE TITLE
[Devel] Use rust-vmm/vm-superio|linux-loader|event-manager|vmm-sys-util

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#1182]
The next round of crates/modules where we can replace the in-tree Firecracker implementation with the upstream [rust-vmm](https://github.com/rust-vmm/community) implementation are:

- [x] [rust-vmm/linux-loader](https://github.com/rust-vmm/linux-loader),
- [x] [rust-vmm/event-manager](https://github.com/rust-vmm/event-manager),
- [x] [rust-vmm/vm-superio](https://github.com/rust-vmm/vm-superio), for the serial console, and RTC device
- [ ] Metrics implementation from [rust-vmm/vmm-sys-util](https://github.com/rust-vmm/vmm-sys-util).
- [x] [rust-vmm/vm-memory](https://github.com/rust-vmm/vm-memory)

**Comment by raduweiss** [comment]
Added linux-loader and event-manager to the list.

**Comment by acatangiu** [comment]
event-manager PR is up: https://github.com/firecracker-microvm/firecracker/pull/2604

**Comment by dianpopa** [comment]
We are using all the crates specified in the issue description except for the metrics. However, we have a separate issue opened for that one: https://github.com/firecracker-microvm/firecracker/issues/1759.
