### ISSUE TITLE
[Devel] Firecracker release improvements bundle 1

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#1183]
Included:
- [x] Firecracker release support policy;
- [x] Firecracker roadmap with "coming soon (= next release)" track.
- [x] Ensure reproducible builds; 
- [x] Keep documentation in sync with the latest release.

Moved to bundle 2:
- [ ] Sign Firecracker release artifacts;
- [ ] Automate the releases process.
