### ISSUE TITLE
Outstanding decoupling-related issues post-merge of 'refactoring/epoll_handler'

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1626]
List:
- [x] #1595 Add unit tests for virtio/mmio.rs
- [x] #1619 Switch Block device to the generic mmio registration path
- [x] #1620 Unify virtio device activation path
- [x] #1621 Add tests for NetworkInterfaceConfig and BlockDeviceConfig
- [x] #1623 Add tests for vmm::controller.rs
- [x] #1624 Add tests for vmm::lib.rs
- [x] #1641 Add unit tests form vmm/resources.rs
- [x] #1631 Check that device performance is not degraded.

**Comment by raduiliescu** [comment]
All the issues were solved.
