### ISSUE TITLE
Implement (de)serialization for the data representation of kvm_vm and kvm_vcpu

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1782]
- [ ] consume `versionize` and `versionize_derive` from firecracker-microvm crates #1830
- [x] add versioning for x86_64 kvm bindings #1829 
- [ ] consume versionized `kvm-ioctls` from firecracker-microvm #1831
- [ ] Implement or derive `Versionize` for `VmState` and `VcpuState`
