### ISSUE TITLE
micro-http: add more flexibility when parsing the headers

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1976]
When we are parsing headers with micro-http, we expect them to be formatted as follows:

``` ${HEADER_NAME} : SPACE ${HEADER_VALUE}```

This breaks some HTTP clients that are more flexible and don't require a space after ":" in the header definition.

## Steps to reproduce:

Input:
```bash
curl --unix-socket /tmp/firecracker.socket -i \
     -X PUT "http://localhost/machine-config" \
     -H "accept:application/json" \
     -H "Content-Type: application/json" \
     -d "{ 
            \"vcpu_count\": 1, 
            \"mem_size_mib\": 3906, 
            \"ht_enabled\": false
        }"
```
The output is:
```
HTTP/1.1 400 
Server: Firecracker API
Connection: keep-alive
Content-Type: application/json
Content-Length: 80

{ "error": "Invalid header.
All previous unanswered requests will be dropped." }
```

The expected behavior is for the curl request to be successful.

## TODO
- [x] allow both formats for header lines: ``` ${HEADER_NAME} : SPACE ${HEADER_VALUE}``` and ``` ${HEADER_NAME} :  ${HEADER_VALUE}```
- [x] add regression test to validate that both formats work
- [ ] [optional-ish] make the error "Invalid header" a bit more useful. Invalid header can mean a lot of things. When a request is sent with multiple headers, it would be nice to at least print which of the headers is the one that's not correct.

**Comment by aghecenco** [comment]
First 2 handled by #1983

**Comment by AlexandruCihodaru** [comment]
I am interested in working on the 3rd part of this issue. Is it ok if I start working on it ?
