### ISSUE TITLE
[Perf] Use virtio event notification supression to improve Firecracker emulated IO/network performance

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#2478]
# Feature Request

Improve Firecracker emulated network/IO performance via virtio event notification suppression.

## Describe the desired solution

Use virtio event notification suppression to improve Firecracker emulated IO performance. This should be transparent to Firecracker users.

## Describe possible alternatives

There are many approaches to improving Firecracker emulated IO/network performance. This is one of them. While this was prototyped together with io_uring, io_uring will work both with and without.

## Additional context

Related issues: #1408, #1529, #1600

[PoC here](https://github.com/alexandruag/firecracker/tree/q).

## Subtasks

- [x] [[Perf] Use virtio event notification supression for the block device](#2635)
- [x] [[Perf] Use virtio event notification supression for the network device](#2636)

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by serban300** [comment]
Adding another related issue: #410

**Comment by bchalios** [comment]
#2934 completed this item. Closing.
