### ISSUE TITLE
Restful API

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#3]
Firecracker is controlled via a RESTful API.

- [x] Figure out how to pass file descriptors atomically within the API message. #14 
- [x] Create API definition #4 
- [ ] Implement the application program interface #15
