### ISSUE TITLE
Replace hyper with custom API implementation

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#615]
Enhance the micro_http in order to replace hyper with it. The reason for doing this is to get rid of the multiple transient dependencies that come with hyper and tokio.

- [x] enhance micro_http implementation: #1191 
- [x] implement HTTP Connection: #1192
- [ ] implement HTTP Server: #1193
- [ ] plumbing to get rid of hyper dependency: #1194
